import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { createPublicClient, http, formatEther } from "viem";
import { celoAlfajores } from "viem/chains";
import fs from "fs";
import path from "path";

// 1. Gera chave privada e conta
const privateKey = generatePrivateKey();
const account = privateKeyToAccount(privateKey);
const address = account.address;

console.log("🌊 LiquidAI Wallet Generator (Celo Alfajores)");
console.log("---------------------------------------------");
console.log(`🔑 Private Key: ${privateKey}`);
console.log(`pub Address:     ${address}`);
console.log("---------------------------------------------");

// 2. Tenta conectar na testnet para validar (mesmo sem saldo)
// Usando RPC alternativo para evitar falhas do Forno
const rpcUrl = "https://alfajores-forno.celo-testnet.org";

const client = createPublicClient({
  chain: celoAlfajores,
  transport: http(rpcUrl),
});

async function checkBalance() {
  try {
    const balance = await client.getBalance({ address });
    console.log(`💰 Balance:     ${formatEther(balance)} CELO`);
    if (balance === 0n) {
      console.log("\n⚠️  Esta carteira está vazia! Você precisa de fundos de teste.");
      console.log("👉 Use o Faucet: https://faucet.celo.org/alfajores");
      console.log(`   Endereço para colar no faucet: ${address}`);
    }
  } catch (err) {
    console.error("Erro ao checar saldo (mas .env foi gerado):", err.message);
  }
}

// 3. Atualiza ou cria .env.local
const envPath = path.resolve(process.cwd(), ".env.local");
let envContent = "";

if (fs.existsSync(envPath)) {
  envContent = fs.readFileSync(envPath, "utf-8");
}

// Remove configurações antigas de chain/key se existirem
envContent = envContent
  .split("\n")
  .filter(line => !line.startsWith("CELO_CHAIN=") && !line.startsWith("CELO_RPC_URL=") && !line.startsWith("PRIVATE_KEY="))
  .join("\n");

// Adiciona as novas configs
const newConfig = `
# Auto-generated by scripts/generate-wallet.mjs
CELO_CHAIN=alfajores
CELO_RPC_URL=${rpcUrl}
PRIVATE_KEY=${privateKey}
`;

fs.writeFileSync(envPath, envContent + newConfig);

console.log(`\n✅ Arquivo .env.local atualizado com sucesso!`);
console.log(`   Chain: Alfajores`);
console.log(`   RPC:   ${rpcUrl}`);

checkBalance();
