export const ECOSYSTEM_RADAR = [
  {
    id: "minipay",
    name: "MiniPay",
    layer: "access-ux",
    status: "active",
    note: "Wallet ultraleve para microtransacoes e pagamentos diarios.",
  },
  {
    id: "socialconnect",
    name: "SocialConnect",
    layer: "access-ux",
    status: "planned",
    note: "Resolucao telefone -> carteira para UX estilo PIX.",
  },
  {
    id: "self-protocol",
    name: "Self",
    layer: "access-ux",
    status: "in-progress",
    note: "Proof of humanity com ZK para reduzir risco sybil.",
  },
  {
    id: "mento",
    name: "Mento Protocol",
    layer: "liquidity-swap",
    status: "active",
    note: "Rampa principal para swap atomico cUSD/cEUR/cBRL.",
  },
  {
    id: "uniswap-v3",
    name: "Uniswap v3",
    layer: "liquidity-swap",
    status: "planned",
    note: "Liquidez concentrada para rotas de execucao.",
  },
  {
    id: "curve",
    name: "Curve",
    layer: "liquidity-swap",
    status: "planned",
    note: "Stable swaps de baixa slippage.",
  },
  {
    id: "stcelo",
    name: "stCELO",
    layer: "yield-vaults",
    status: "planned",
    note: "Liquid staking base para estrategia de longo prazo.",
  },
  {
    id: "aave",
    name: "Aave v3",
    layer: "yield-vaults",
    status: "active",
    note: "Lending principal de baixo risco para stablecoins.",
  },
  {
    id: "moola",
    name: "Moola Market",
    layer: "yield-vaults",
    status: "planned",
    note: "Lending nativo Celo para ativos locais.",
  },
  {
    id: "kiln",
    name: "Kiln Finance",
    layer: "yield-vaults",
    status: "planned",
    note: "Vault institucional para composicao de estrategia.",
  },
  {
    id: "untangled",
    name: "Untangled Finance",
    layer: "rwa-credit",
    status: "planned",
    note: "Credito privado tokenizado para alfa com risco controlado.",
  },
  {
    id: "ethichub",
    name: "EthicHub",
    layer: "rwa-credit",
    status: "planned",
    note: "Crowdlending para economia real (agro e PMEs).",
  },
  {
    id: "credit-collective",
    name: "Credit Collective",
    layer: "rwa-credit",
    status: "planned",
    note: "Gestao de liquidez para mercados emergentes.",
  },
  {
    id: "erc-8004",
    name: "ERC-8004",
    layer: "agent-telemetry",
    status: "in-progress",
    note: "Padrao de intencao e identidade portavel para agentes.",
  },
  {
    id: "karma",
    name: "Karma Proof-of-Ship",
    layer: "agent-telemetry",
    status: "active",
    note: "Telemetria e reputacao auditavel do agente.",
  },
  {
    id: "agentscan",
    name: "AgentScan",
    layer: "agent-telemetry",
    status: "planned",
    note: "Ranking e visibilidade das intencoes/execucoes.",
  },
  {
    id: "sortedoracles",
    name: "SortedOracles",
    layer: "agent-telemetry",
    status: "planned",
    note: "Precos medianos/TWAP para prevenir execucao manipulada.",
  },
];
